name: Test prefix

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create branches
        run: |
          git checkout -b test-prefix-1
          git push -f origin test-prefix-1
          git checkout -b test-prefix-2
          git push -f origin test-prefix-2
          git checkout -b test-prefix-3
          git push -f origin test-prefix-3
      - name: Test action
        uses: ./
        with:
          prefix: test-prefix-
