name: Test action

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup hub
        uses: geertvdc/setup-hub@v1.0.0
      - name: Create branches
        run: |
          git checkout -b prefix-test1-suffix
          git push -f origin prefix-test1-suffix
          git checkout -b prefix-test2-suffix
          git push -f origin prefix-test2-suffix
      - name: Test action
        uses: ./
        with:
          branches: test1,test2
          prefix: prefix-
          suffix: -suffix